/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface TodoInterface extends Interface {
    getFunction(nameOrSignature: "cancelTodo" | "createTodo" | "markAsDone" | "todoCounter" | "todos"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "TodoCreated" | "TodoStatusChanged"): EventFragment;

    encodeFunctionData(functionFragment: 'cancelTodo', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createTodo', values: [string, BigNumberish]): string;
encodeFunctionData(functionFragment: 'markAsDone', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'todoCounter', values?: undefined): string;
encodeFunctionData(functionFragment: 'todos', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'cancelTodo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createTodo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'markAsDone', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'todoCounter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'todos', data: BytesLike): Result;
  }

  
    export namespace TodoCreatedEvent {
      export type InputTuple = [id: BigNumberish, text: string, deadline: BigNumberish];
      export type OutputTuple = [id: bigint, text: string, deadline: bigint];
      export interface OutputObject {id: bigint, text: string, deadline: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TodoStatusChangedEvent {
      export type InputTuple = [id: BigNumberish, newStatus: BigNumberish];
      export type OutputTuple = [id: bigint, newStatus: bigint];
      export interface OutputObject {id: bigint, newStatus: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Todo extends BaseContract {
    
    connect(runner?: ContractRunner | null): Todo;
    waitForDeployment(): Promise<this>;

    interface: TodoInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    cancelTodo: TypedContractMethod<
      [_id: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    createTodo: TypedContractMethod<
      [_text: string, _deadline: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    markAsDone: TypedContractMethod<
      [_id: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    todoCounter: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    todos: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, bigint, bigint] & {id: bigint, owner: string, text: string, status: bigint, deadline: bigint }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'cancelTodo'): TypedContractMethod<
      [_id: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createTodo'): TypedContractMethod<
      [_text: string, _deadline: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'markAsDone'): TypedContractMethod<
      [_id: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'todoCounter'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'todos'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, bigint, bigint] & {id: bigint, owner: string, text: string, status: bigint, deadline: bigint }],
      'view'
    >;

    getEvent(key: 'TodoCreated'): TypedContractEvent<TodoCreatedEvent.InputTuple, TodoCreatedEvent.OutputTuple, TodoCreatedEvent.OutputObject>;
getEvent(key: 'TodoStatusChanged'): TypedContractEvent<TodoStatusChangedEvent.InputTuple, TodoStatusChangedEvent.OutputTuple, TodoStatusChangedEvent.OutputObject>;

    filters: {
      
      'TodoCreated(uint256,string,uint256)': TypedContractEvent<TodoCreatedEvent.InputTuple, TodoCreatedEvent.OutputTuple, TodoCreatedEvent.OutputObject>;
      TodoCreated: TypedContractEvent<TodoCreatedEvent.InputTuple, TodoCreatedEvent.OutputTuple, TodoCreatedEvent.OutputObject>;
    

      'TodoStatusChanged(uint256,uint8)': TypedContractEvent<TodoStatusChangedEvent.InputTuple, TodoStatusChangedEvent.OutputTuple, TodoStatusChangedEvent.OutputObject>;
      TodoStatusChanged: TypedContractEvent<TodoStatusChangedEvent.InputTuple, TodoStatusChangedEvent.OutputTuple, TodoStatusChangedEvent.OutputObject>;
    
    };
  }